<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RollForward>Major</RollForward>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../AdofaiIpc.Shim/AdofaiIpc.Shim.csproj" />
    <ProjectReference Include="../AdofaiIpc.Launcher/AdofaiIpc.Launcher.csproj" />
    <Reference Include="UnityModManager">
      <HintPath>$(UnityModManagerDll)</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(AdofaiManaged)/Newtonsoft.Json.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
