#!/usr/bin/env bash

if [ "${ADOFAIIPC_CONTEXT_LOADED:-0}" = "1" ]; then return 0; fi
ADOFAIIPC_CONTEXT_LOADED=1

ADOFAIIPC_LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ADOFAIIPC_PROJECT_ROOT="$(cd "$ADOFAIIPC_LIB_DIR/../.." && pwd)"

if [ -f "$ADOFAIIPC_PROJECT_ROOT/.env" ]; then
  set -a
  # shellcheck disable=SC1091
  source "$ADOFAIIPC_PROJECT_ROOT/.env"
  set +a
fi

ADOFAI_DIR="${ADOFAI_DIR:-$HOME/Library/Application Support/Steam/steamapps/common/A Dance of Fire and Ice}"
ADOFAI_MODS_DIR="${ADOFAI_MODS_DIR:-$ADOFAI_DIR/Mods}"
ADOFAI_MANAGED="${ADOFAI_MANAGED:-$ADOFAI_DIR/ADanceOfFireAndIce.app/Contents/Resources/Data/Managed}"
DOTNET_ROOT="${DOTNET_ROOT:-$HOME/.dotnet}"
DOTNET_ROOT_ARM64="${DOTNET_ROOT_ARM64:-$DOTNET_ROOT}"
DOTNET_EXE="${DOTNET_EXE:-$DOTNET_ROOT/dotnet}"
UNITY_MOD_MANAGER_DLL="${UNITY_MOD_MANAGER_DLL:-$ADOFAI_MANAGED/UnityModManager/UnityModManager.dll}"
HARMONY_DLL="${HARMONY_DLL:-$ADOFAI_MANAGED/UnityModManager/0Harmony.dll}"

project_path() {
  case "$1" in /*) printf '%s\n' "$1" ;; *) printf '%s/%s\n' "$ADOFAIIPC_PROJECT_ROOT" "$1" ;; esac
}

ADOFAIIPC_RUNTIME_OUTPUT="$(project_path "${ADOFAIIPC_BUILD_DIR:-build/AdofaiIpc}")"
ADOFAIIPC_BOOTSTRAP_OUTPUT="$(project_path "${ADOFAIIPC_BOOTSTRAP_BUILD_DIR:-build/AdofaiIpc.Bootstrap}")"
ADOFAIIPC_SHIM_OUTPUT="$(project_path "${ADOFAIIPC_SHIM_BUILD_DIR:-build/AdofaiIpc.DependencyShim}")"
ADOFAIIPC_RUNTIME_SHIM_OUTPUT="$(project_path "${ADOFAIIPC_RUNTIME_SHIM_BUILD_DIR:-build/AdofaiIpc.Shim}")"
ADOFAIIPC_LAUNCHER_OUTPUT="$(project_path "${ADOFAIIPC_LAUNCHER_BUILD_DIR:-build/AdofaiIpc.Launcher}")"
ADOFAIIPC_MIGRATION_OUTPUT="$(project_path "${ADOFAIIPC_MIGRATION_BUILD_DIR:-build/AdofaiIpc.Migration}")"
ADOFAIIPC_INSTALL_PATH="$(project_path "${ADOFAIIPC_INSTALL_DIR:-$ADOFAI_MODS_DIR/AdofaiIpc}")"
ADOFAIIPC_PACKAGE_ROOT="$(project_path "${ADOFAIIPC_PACKAGE_ROOT:-build/package}")"
ADOFAIIPC_PACKAGE_STAGE="$ADOFAIIPC_PACKAGE_ROOT/AdofaiIpc"
ADOFAIIPC_PACKAGE_ZIP="$(project_path "${ADOFAIIPC_PACKAGE_ZIP:-build/AdofaiIpc.zip}")"

export ADOFAIIPC_PROJECT_ROOT ADOFAI_DIR ADOFAI_MODS_DIR ADOFAI_MANAGED
export DOTNET_ROOT DOTNET_ROOT_ARM64 DOTNET_EXE UNITY_MOD_MANAGER_DLL HARMONY_DLL
export ADOFAIIPC_RUNTIME_OUTPUT ADOFAIIPC_BOOTSTRAP_OUTPUT ADOFAIIPC_SHIM_OUTPUT
export ADOFAIIPC_RUNTIME_SHIM_OUTPUT ADOFAIIPC_LAUNCHER_OUTPUT
export ADOFAIIPC_MIGRATION_OUTPUT
export ADOFAIIPC_INSTALL_PATH ADOFAIIPC_PACKAGE_ROOT ADOFAIIPC_PACKAGE_STAGE ADOFAIIPC_PACKAGE_ZIP
